"""Curated rap slang lexicon.

Each entry:
  id        stable key used in every derived table and on the site
  label     how the term is displayed
  cat       category
  gloss     short meaning in the rap sense (our own wording)
  tokens    single-token spellings matched against a song's word set (lowercased,
            internal apostrophes kept, trailing apostrophes dropped: "gettin'" -> "gettin")
  phrases   multi-word regexes matched against the lowercased lyric text; spaces become \\s+
  poly      True when the spelling also has an older standard-English meaning, so a raw
            count mixes senses (these get meaning-shift treatment instead of face value)
  region    scene the term is conventionally associated with (a hypothesis the regional
            analysis tests, not an input to it)

Slurs are deliberately left out of the lexicon.
"""

T = []


def term(id, label, cat, gloss, tokens=(), phrases=(), poly=False, region=None):
    T.append(dict(id=id, label=label, cat=cat, gloss=gloss, tokens=list(tokens),
                  phrases=list(phrases), poly=poly, region=region))


# --- Praise, style, hype -------------------------------------------------------------
term("phat", "phat", "praise", "excellent, great", ["phat", "phatt", "phattest"])
term("dope", "dope", "praise", "excellent (also: drugs)", ["dope", "dopest"], poly=True)
term("fly", "fly", "praise", "stylish, attractive", ["fly", "flyest", "flyy"], poly=True)
term("fresh", "fresh", "praise", "stylish, new, cool", ["fresh", "freshest"], poly=True)
term("dabomb", "da bomb", "praise", "the best", phrases=[r"da bomb", r"tha bomb"])
term("tight", "tight", "praise", "excellent; also close-knit", ["tight"], poly=True)
term("jiggy", "jiggy", "praise", "flashy, stylish (late-90s)", ["jiggy", "jiggyness", "jiggie"])
term("bling", "bling", "flex", "flashy jewelry and wealth", ["bling", "blingin", "blingy", "blinging"])
term("swag", "swag", "praise", "style, confidence", ["swag", "swagg", "swaggin", "swagged", "swaggy"])
term("drip", "drip", "praise", "fashionable outfit / style", ["drip", "drippin", "dripping", "drippy", "dripped"], poly=True)
term("sauce", "sauce", "praise", "style, swagger", ["sauce", "saucy", "saucin", "saucing", "sauced"], poly=True)
term("wavy", "wavy", "praise", "cool, stylish; also high", ["wavy", "wavey"])
term("fire", "fire", "praise", "excellent", ["fire", "fye", "fiyah"], poly=True)
term("lit", "lit", "praise", "exciting, wild; also drunk/high", ["lit", "litty"], poly=True)
term("turnt", "turnt", "party", "hyped up, intoxicated", ["turnt", "turnup"], phrases=[r"turnt up"])
term("hyphy", "hyphy", "party", "Bay Area hyperactive party style", ["hyphy"], region="Bay Area")
term("crunk", "crunk", "party", "hyped, rowdy; Southern party rap", ["crunk", "crunked", "krunk"], region="Atlanta / Memphis")
term("trill", "trill", "praise", "true and real", ["trill", "trillest"], region="Houston")
term("throwed", "throwed", "praise", "wild, impressive; high", ["throwed", "thowed"], region="Houston")
term("stuntin", "stuntin", "flex", "showing off", ["stuntin", "stunting", "stunna", "stunner"])
term("flexin", "flexin", "flex", "showing off", ["flexin", "flexing", "flex", "flexed"], poly=True)
term("ballin", "ballin", "flex", "living rich", ["ballin", "balling", "baller", "ballers"])
term("icy", "icy", "flex", "covered in diamonds", ["icy", "icey"], phrases=[r"iced (?:out|up)"], poly=True)
term("bussin", "bussin", "praise", "really good (Gen Z sense); older: shooting", ["bussin", "bussing"], poly=True)
term("valid", "valid", "praise", "legit, good", ["valid"], poly=True)
term("goat", "GOAT", "praise", "greatest of all time", ["goated"], phrases=[r"the goat", r"g\.o\.a\.t"], poly=True)
term("sheesh", "sheesh", "adlib", "exclamation of amazement", ["sheesh", "sheeesh", "sheeeesh"])
term("lowkey", "lowkey", "talk", "quietly, secretly; somewhat", ["lowkey"], phrases=[r"low[\s-]key"])
term("vibe", "vibe", "talk", "mood, atmosphere", ["vibe", "vibes", "vibin", "vibing"], poly=True)
term("boujee", "boujee", "flex", "bougie, high-class", ["boujee", "bougie", "bourgie", "bougee", "boujie"])
term("ratchet", "ratchet", "people", "wild, ghetto, messy", ["ratchet", "ratchets"])
term("savage", "savage", "praise", "ruthless, fearless", ["savage", "savages", "savagery"], poly=True)
term("goofy", "goofy", "diss", "foolish person", ["goofy", "goofies"], poly=True)

# --- Agreement, emphasis, speech -------------------------------------------------------
term("nocap", "no cap", "talk", "no lie, for real", ["nocap"], phrases=[r"no cap\b"])
term("cappin", "cappin", "talk", "lying", ["cappin", "capping", "capper"], poly=True)
term("ongod", "on god", "talk", "I swear", phrases=[r"on god\b"])
term("ong", "ong", "talk", "on god (abbrev.)", ["ong"])
term("ongang", "on gang", "talk", "I swear (on my crew)", phrases=[r"on gang\b"])
term("onmymama", "on my mama", "talk", "I swear", phrases=[r"on my (?:mama|momma|mom|mother)\b"])
term("deadass", "deadass", "talk", "seriously, for real", ["deadass"], region="New York City")
term("forreal", "fr / for real", "talk", "seriously", ["fr", "frfr"], phrases=[r"for real for real"])
term("bigfacts", "facts", "talk", "that's true", ["facts"], phrases=[r"big facts"], poly=True)
term("wordup", "word up", "talk", "agreed, truly", phrases=[r"word up", r"word to (?:my |your |ya )?(?:mother|moms|mama)", r"word is bond", r"word life"], region="New York City")
term("fosho", "fo sho", "talk", "for sure", ["fosho", "foshizzle"], phrases=[r"fo'? sho'?"])
term("izzle", "-izzle", "talk", "Snoop-style izzle speak", ["shizzle", "fashizzle", "foshizzle", "shiznit", "hizzle", "hizzouse"], region="Los Angeles")
term("yadadamean", "yadadamean", "talk", "you know what I mean", ["yadadamean", "yadamean", "knahmean", "nahmean", "nahmsayin", "knamsayin", "nahmsaying", "ynmsayin"])
term("yadig", "ya dig", "talk", "you understand?", ["yadig"], phrases=[r"ya dig\b", r"you dig\b"], region="New Orleans / Houston")
term("mane", "mane", "talk", "man (address)", ["mane", "mayne"], poly=True, region="Memphis / Houston")
term("finna", "finna", "talk", "about to", ["finna", "fitna"])
term("boutta", "boutta", "talk", "about to", ["boutta", "bouta", "abouta"])
term("tryna", "tryna", "talk", "trying to", ["tryna", "trynna", "tryin'a"])
term("ion", "ion", "talk", "I don't", ["ion"], poly=True)
term("issa", "issa", "talk", "it's a", ["issa"])
term("periodt", "periodt", "talk", "end of discussion", ["periodt", "periodttt"])
term("hella", "hella", "talk", "very, a lot", ["hella", "hecka", "hellafied"], region="Bay Area")
term("jawn", "jawn", "talk", "thing, person, anything", ["jawn", "jawns", "jont", "jonts"], region="Philadelphia / DMV")
term("son", "son", "talk", "address to a peer", phrases=[r"\byo,? son\b", r"\bson!"], poly=True, region="New York City")
term("yerr", "yerr", "talk", "hey! (greeting)", ["yerr", "yurr", "yerrr", "yurrr"], region="New York City")
term("sayless", "say less", "talk", "understood, deal", phrases=[r"say less"])
term("sus", "sus", "talk", "suspicious", ["sus"], poly=True)
term("salty", "salty", "talk", "bitter, upset", ["salty"], poly=True)
term("thirsty", "thirsty", "talk", "desperate for attention", ["thirsty", "thirst"], poly=True)
term("woke", "woke", "talk", "socially aware", ["woke"], poly=True)
term("shade", "shade", "talk", "disrespect", ["shade", "shadin", "shading"], poly=True)
term("stan", "stan", "people", "obsessive fan", ["stan", "stans", "stanning"], poly=True)
term("yolo", "YOLO", "talk", "you only live once", ["yolo"])
term("onfleek", "on fleek", "talk", "perfect", ["fleek"])
term("bae", "bae", "people", "sweetheart", ["bae"])

# --- People ---------------------------------------------------------------------------
term("shawty", "shawty", "people", "girl, young woman (Southern spelling)", ["shawty", "shawtie", "shordy", "shawdy"], region="Atlanta")
term("shorty", "shorty", "people", "girl, young woman; kid (older spelling)", ["shorty", "shortie", "shortys"], poly=True, region="New York City")
term("wifey", "wifey", "people", "main girlfriend", ["wifey", "wifeys"])
term("boo", "boo", "people", "significant other", phrases=[r"my boo\b"])
term("baddie", "baddie", "people", "attractive, confident woman", ["baddie", "baddies"])
term("thot", "thot", "people", "promiscuous woman (derogatory)", ["thot", "thots", "thottie", "thotties", "thotty"], region="Chicago")
term("dimepiece", "dime", "people", "very attractive woman", ["dimepiece", "dimes"], phrases=[r"\ba dime\b"], poly=True)
term("jit", "jit", "people", "young kid", ["jit", "jits", "jitt"], region="Florida")
term("homie", "homie", "people", "friend", ["homie", "homies", "homey", "homeboy", "homeboys", "holmes"])
term("dawg", "dawg", "people", "friend", ["dawg", "dawgs"])
term("fam", "fam", "people", "close friend(s)", ["fam"])
term("bruh", "bruh", "people", "bro", ["bruh", "breh", "brah"])
term("brodie", "brodie", "people", "close friend", ["brodie", "brody", "broski"])
term("twin", "twin", "people", "best friend", ["twin", "twinnem"], poly=True)
term("gang", "gang", "people", "crew; ad-lib", ["gang"], poly=True)
term("slime", "slime", "people", "loyal friend (Atlanta)", ["slime", "slimes", "slimey", "slimy"], poly=True, region="Atlanta")
term("opps", "opps", "people", "enemies, rivals", ["opp", "opps", "oppas"], region="Chicago")
term("haters", "haters", "people", "jealous detractors", ["haters", "hater", "hatin", "hating", "haterade"])
term("busta", "busta", "diss", "fake, weak person", ["busta", "bustas", "buster", "busters"])
term("sucka", "sucka", "diss", "weak, fake person", ["sucka", "suckas", "sucker", "suckers"], poly=True)
term("lame", "lame", "diss", "uncool person", ["lame", "lames"], poly=True)
term("herb", "herb", "diss", "weak, soft person", ["herb", "herbs"], poly=True, region="New York City")
term("simp", "simp", "diss", "man overly devoted to a woman", ["simp", "simpin", "simping", "simps"])
term("snitch", "snitch", "diss", "informant", ["snitch", "snitches", "snitchin", "snitching"])
term("playa", "playa", "people", "player, ladies' man", ["playa", "playas", "playaz"])
term("mack", "mack", "people", "pimp, smooth talker", ["mack", "mackin", "macking", "macks"], poly=True, region="Bay Area")
term("skeezer", "skeezer", "people", "promiscuous woman (derogatory, 80s-90s)", ["skeezer", "skeezers", "skeeze", "skeezin"])
term("mandem", "mandem", "people", "group of male friends (UK)", ["mandem", "gyaldem"], region="UK")
term("bruv", "bruv", "people", "brother (UK)", ["bruv", "bruva"], region="UK")
term("ting", "ting", "people", "girl, thing (UK/Caribbean)", ["ting", "tings"], region="UK")
term("peng", "peng", "praise", "attractive (UK)", ["peng", "pengest"], region="UK")
term("innit", "innit", "talk", "isn't it (UK)", ["innit"], region="UK")
term("wagwan", "wagwan", "talk", "what's going on (UK/Jamaican)", ["wagwan"], phrases=[r"wah gwan"], region="UK")

# --- Money ----------------------------------------------------------------------------
term("cheddar", "cheddar", "money", "money", ["cheddar"])
term("cheese", "cheese", "money", "money", ["cheese"], poly=True)
term("scrilla", "scrilla", "money", "money", ["scrilla", "skrilla", "scrill", "skrill"])
term("fetti", "fetti", "money", "money", ["fetti", "feddi", "fedi", "feddy"], region="Bay Area")
term("cream", "cream", "money", "money (C.R.E.A.M.)", ["cream"], poly=True, region="New York City")
term("paper", "paper", "money", "money", ["paper"], poly=True)
term("bread", "bread", "money", "money", ["bread"], poly=True)
term("guap", "guap", "money", "lots of money", ["guap", "gwap", "gwop", "guwop"])
term("bands", "bands", "money", "$1,000 bundles", ["bands"], poly=True)
term("racks", "racks", "money", "$1,000 stacks", ["racks", "rackies"])
term("hunnids", "hunnids", "money", "hundred-dollar bills", ["hunnid", "hunnids", "hunnit", "hunnits", "hundos"])
term("benjamins", "benjamins", "money", "hundred-dollar bills", ["benjamins", "benjis", "benjies", "benji"])
term("deadpresidents", "dead presidents", "money", "cash", phrases=[r"dead presidents"])
term("commas", "commas", "money", "big money", ["commas"])
term("bag", "the bag", "money", "money, a big payday", phrases=[r"(?:secure|securin|securing|get|gettin|getting|chase|chasin|chasing|in) (?:the|a|my) bag\b", r"bag secured"], poly=True)
term("mula", "mula", "money", "money", ["mula", "moolah", "moola"])
term("knots", "knots", "money", "rolls of cash", ["knots", "knot"], poly=True)
term("bankroll", "bankroll", "money", "big stack of cash", ["bankroll", "bankrolls"])
term("bluefaces", "blue faces", "money", "new $100 bills", ["blueface", "bluefaces", "blueies", "bluies"], phrases=[r"blue faces", r"blue strips", r"blue hunnids"])
term("loot", "loot", "money", "money", ["loot"], poly=True)
term("ends", "ends", "money", "money", phrases=[r"\bmake (?:some|a few|my) ends\b"])
term("chips", "chips", "money", "money", ["chips"], poly=True)
term("cake", "cake", "money", "money", ["cake"], poly=True)

# --- Drugs & drink --------------------------------------------------------------------
term("indo", "indo", "drugs", "high-grade weed (90s)", ["indo", "endo"], region="Los Angeles")
term("chronic", "chronic", "drugs", "high-grade weed", ["chronic"], poly=True)
term("blunts", "blunts", "drugs", "cigar-wrapped weed", ["blunt", "blunts"], poly=True)
term("dro", "dro", "drugs", "hydroponic weed", ["dro", "hydro"])
term("kush", "kush", "drugs", "weed strain", ["kush"])
term("purp", "purp", "drugs", "purple weed / lean", ["purp"])
term("loud", "loud", "drugs", "strong-smelling weed", phrases=[r"(?:smok|roll|blow|pack|burn|pass)(?:e|ed|in|ing|es)? (?:up )?(?:some |that |the |a |my )?loud\b", r"loud pack"], poly=True)
term("gas", "gas", "drugs", "strong weed; hype", ["gas", "gassed", "gassin", "gassing", "gasoline"], poly=True)
term("zaza", "za / zaza", "drugs", "exotic weed", ["zaza", "za"])
term("runtz", "runtz", "drugs", "weed strain", ["runtz"])
term("backwoods", "backwoods", "drugs", "cigar wraps", ["backwoods", "backwood", "woodz"])
term("lean", "lean", "drugs", "codeine syrup drink", ["lean", "leanin"], poly=True, region="Houston")
term("sizzurp", "sizzurp", "drugs", "codeine syrup drink", ["sizzurp", "syrup", "drank", "barre"], poly=True, region="Houston")
term("wock", "wock", "drugs", "Wockhardt codeine", ["wock", "wockhardt", "wockesha", "wocky", "wockstar"])
term("codeine", "codeine", "drugs", "opiate syrup", ["codeine", "tussin", "promethazine", "actavis"], poly=True)
term("molly", "molly", "drugs", "MDMA", ["molly", "mollies", "mollys"], poly=True)
term("percs", "percs", "drugs", "Percocet", ["perc", "percs", "perky", "perkys", "percocet", "percocets", "perky's", "percys"])
term("xans", "xans", "drugs", "Xanax", ["xan", "xans", "xanny", "xannies", "xanax", "xanies"])
term("addy", "addy", "drugs", "Adderall", ["addy", "adderall", "addys"])
term("yola", "yola", "drugs", "cocaine", ["yola", "yayo", "yeyo", "perico"])
term("work", "work", "drugs", "drugs to sell", phrases=[r"(?:cook|whip|flip|move|serv|push)(?:in|ing|ed|e|es)? (?:the |that |some |up )?work\b"], poly=True)
term("trap", "trap", "drugs", "drug house; drug dealing", ["trap", "trappin", "trapping", "trapper", "trappers", "traphouse", "trapstar"], poly=True, region="Atlanta")
term("bando", "bando", "drugs", "abandoned house used to deal", ["bando", "bandos", "bandz"], region="Atlanta")
term("plug", "plug", "drugs", "supplier, connect", ["plug", "plugs", "plugged"], poly=True)
term("henny", "henny", "drugs", "Hennessy cognac", ["henny", "hennessy", "hennesy"])
term("forty", "40 oz", "drugs", "malt liquor bottle", ["40oz", "40s"], phrases=[r"forty (?:ounce|oz)", r"40 (?:ounce|oz)"])

# --- Luxury & brands ------------------------------------------------------------------
term("cristal", "Cristal", "brands", "Champagne", ["cristal", "crissy"])
term("moet", "Moët", "brands", "Champagne", ["moet"], phrases=[r"moët"])
term("aceofspades", "Ace of Spades", "brands", "Champagne", phrases=[r"ace of spades", r"\barmand\b"])
term("patron", "Patrón", "brands", "tequila", ["patron"], phrases=[r"patrón"], poly=True)
term("versace", "Versace", "brands", "fashion house", ["versace", "versaces"])
term("gucci", "Gucci", "brands", "fashion house", ["gucci"], poly=True)
term("prada", "Prada", "brands", "fashion house", ["prada"])
term("louis", "Louis Vuitton", "brands", "fashion house", ["vuitton", "louie"], phrases=[r"louis v\b"])
term("balenciaga", "Balenciaga", "brands", "fashion house", ["balenciaga", "balenci", "balenciagas"])
term("givenchy", "Givenchy", "brands", "fashion house", ["givenchy"])
term("amiri", "Amiri", "brands", "fashion brand", ["amiri", "amiris"])
term("vlone", "Vlone", "brands", "streetwear brand", ["vlone"])
term("bape", "Bape", "brands", "streetwear brand", ["bape", "bapes"])
term("redbottoms", "red bottoms", "brands", "Louboutin shoes", ["louboutin", "louboutins", "loubs"], phrases=[r"red bottoms?"])
term("chanel", "Chanel", "brands", "fashion house", ["chanel"])
term("fendi", "Fendi", "brands", "fashion house", ["fendi"])
term("dior", "Dior", "brands", "fashion house", ["dior"])
term("hermes", "Hermès / Birkin", "brands", "luxury handbags", ["hermes", "birkin", "birkins"])
term("rolex", "Rolex", "brands", "watch", ["rolex", "rollie", "rollies", "rolly", "rolexes"])
term("patek", "Patek", "brands", "Patek Philippe watch", ["patek", "pateks", "philippe"])
term("ap", "Audemars Piguet", "brands", "AP watch", ["audemars", "piguet"])
term("richardmille", "Richard Mille", "brands", "watch", phrases=[r"richard mille"])
term("cartier", "Cartier", "brands", "jeweler; Cartier glasses", ["cartier", "cartiers", "buffs", "buffies"])
term("maybach", "Maybach", "brands", "luxury car", ["maybach", "maybachs"])
term("bentley", "Bentley", "brands", "luxury car", ["bentley", "bentleys", "bentayga"])
term("lambo", "Lamborghini", "brands", "sports car", ["lambo", "lambos", "lamborghini", "lamborghinis", "urus"])
term("benz", "Benz", "brands", "Mercedes-Benz", ["benz", "benzo", "benzes", "mercedes"])
term("rover", "Range Rover", "brands", "SUV", ["rover", "rovers"], phrases=[r"range rover"])
term("phantom", "Rolls-Royce", "brands", "luxury car", ["wraith", "wraiths", "royce"])
term("bugatti", "Bugatti", "brands", "supercar", ["bugatti", "bugattis"])
term("tesla", "Tesla", "brands", "electric car", ["tesla", "teslas"])
term("hellcat", "Hellcat", "brands", "Dodge muscle car", ["hellcat", "hellcats", "trackhawk", "trackhawks"])
term("escalade", "Cadillac", "brands", "Cadillac / Escalade", ["escalade", "escalades", "cadillac", "cadillacs"])
term("impala", "Impala / Cutlass", "brands", "classic lowrider cars", ["impala", "impalas", "cutlass", "lowrider", "lowriders"])
term("slab", "slab", "flex", "Houston candy-painted car", ["slab", "slabs", "swangas", "swangin", "elbows"], region="Houston")
term("rims", "rims", "flex", "wheels (dubs, 24s)", ["rims", "dubs", "spinners", "24s", "26s", "28s"])
term("grillz", "grillz", "flex", "gold/diamond teeth", ["grillz", "grills", "fronts", "golds"], poly=True)
term("vvs", "VVS", "flex", "flawless diamonds", ["vvs", "vvs's", "vvs1", "vvss"])
term("baguettes", "baguettes", "flex", "rectangular diamonds", ["baguettes", "baguette"])
term("bustdown", "bust down", "flex", "fully iced watch", ["bustdown", "busdown"], phrases=[r"bust ?down"])
term("flooded", "flooded", "flex", "covered in diamonds", ["flooded"], poly=True)

# --- Guns & violence ------------------------------------------------------------------
term("gat", "gat", "guns", "gun", ["gat", "gats", "gatt"])
term("tec", "tec", "guns", "TEC-9 pistol", ["tec", "tecs"], phrases=[r"\btec\s*-?\s*9\b", r"\btec\s*-?\s*nine\b"])
term("glock", "glock", "guns", "Glock pistol", ["glock", "glocks", "glocky"])
term("mac", "MAC-10/11", "guns", "machine pistol", phrases=[r"\bmac\s*-?\s*1[01]\b", r"\bmac\s*-?\s*(?:ten|eleven)\b"])
term("choppa", "choppa", "guns", "assault rifle", ["choppa", "choppas", "chopper", "choppers"], poly=True)
term("draco", "draco", "guns", "Draco AK pistol", ["draco", "dracos", "drac", "dracs"])
term("blicky", "blicky", "guns", "gun (NY drill)", ["blicky", "blickys", "blick", "blicks", "blickies"], region="New York City")
term("glizzy", "glizzy", "guns", "Glock", ["glizzy", "glizzys", "glizzies"])
term("stick", "stick", "guns", "rifle, gun", ["stick", "sticks"], poly=True)
term("pole", "pole", "guns", "gun", ["pole", "poles"], poly=True)
term("switch", "switch", "guns", "auto-sear converting a Glock", ["switch", "switches"], poly=True)
term("strap", "strap", "guns", "gun", ["strap", "strapped", "straps"], poly=True)
term("burner", "burner", "guns", "gun", ["burner", "burners"], poly=True)
term("extendo", "extendo", "guns", "extended magazine", ["extendo", "extendos"])
term("ruger", "ruger", "guns", "Ruger pistol", ["ruger", "rugers"])
term("smoke", "smoke", "violence", "conflict, beef (\"want smoke\")", phrases=[r"(?:want|wants|want no|don't want|got|with the|ain't want) smoke\b"], poly=True)
term("drill", "drill", "violence", "to shoot; drill music", ["drill", "drillin", "drilling", "driller", "drillers"], poly=True, region="Chicago")
term("slide", "slide", "violence", "drive-by, pull up to fight", ["slide", "slidin", "sliding"], poly=True)
term("pressure", "pressure", "violence", "threat, aggression", phrases=[r"apply (?:the |some )?pressure"], poly=True)
term("bodied", "bodied", "violence", "killed; outperformed", ["bodied", "bodyin", "bodying"], poly=True)

# --- Tech & media ---------------------------------------------------------------------
term("pager", "pager", "tech", "pager, beeper", ["pager", "pagers", "beeper", "beepers", "skypager"])
term("twoway", "two-way", "tech", "two-way pager / Sidekick", ["2way", "sidekick", "blackberry", "blackberrys", "chirp", "nextel"], phrases=[r"two[\s-]way"])
term("myspace", "MySpace", "tech", "social network", ["myspace"])
term("facebook", "Facebook", "tech", "social network", ["facebook"])
term("twitter", "Twitter", "tech", "social network", ["twitter", "tweet", "tweets", "tweetin", "tweeting", "retweet"])
term("instagram", "Instagram", "tech", "social network", ["instagram", "insta", "ig"])
term("snapchat", "Snapchat", "tech", "social network", ["snapchat"])
term("tiktok", "TikTok", "tech", "social video app", ["tiktok"], phrases=[r"tik[\s-]tok"], poly=True)
term("facetime", "FaceTime", "tech", "video call", ["facetime", "facetimin", "facetiming"])
term("dm", "DMs", "tech", "direct messages", ["dm", "dms", "dm's", "dmed", "dming"])
term("soundcloud", "SoundCloud", "tech", "music platform", ["soundcloud"])
term("youtube", "YouTube", "tech", "video platform", ["youtube"])
term("streams", "streams", "tech", "streaming numbers", ["streams", "streaming", "spotify"], poly=True)
term("mixtape", "mixtape", "tech", "mixtape", ["mixtape", "mixtapes"])
term("covid", "COVID / pandemic", "tech", "COVID-19 pandemic", ["covid", "corona", "coronavirus", "pandemic", "quarantine", "quarantined"])
term("crypto", "crypto", "tech", "cryptocurrency", ["crypto", "bitcoin", "bitcoins", "nft", "nfts", "ethereum"])

# --- Ad-libs & dances -----------------------------------------------------------------
term("skrrt", "skrrt", "adlib", "tire screech", ["skrrt", "skrt", "skrr", "skrrr", "skrrrt", "skurt", "skrrrr"])
term("brr", "brr", "adlib", "gunfire / cold", ["brr", "brrt", "brrr", "brrrt", "brrrr", "grr", "grrah", "grrt"])
term("baow", "baow", "adlib", "gunshot ad-lib", ["baow", "baoww", "boaw"])
term("slatt", "slatt", "adlib", "Slime love all the time (YSL)", ["slatt", "slat", "slattt"], region="Atlanta")
term("eskeetit", "esskeetit", "adlib", "let's get it (Lil Pump)", ["esskeetit", "eskeetit", "esketit", "eskeetitt"])
term("yeet", "yeet", "adlib", "exclamation; throw", ["yeet"])
term("dab", "dab", "dance", "dab dance move; also wax concentrate", ["dab", "dabbin", "dabbing", "dabs"], poly=True, region="Atlanta")
term("naenae", "nae nae", "dance", "dance craze", phrases=[r"nae nae"])
term("stankyleg", "stanky leg", "dance", "dance craze", phrases=[r"stanky leg"])
term("twerk", "twerk", "dance", "dance", ["twerk", "twerkin", "twerking", "twerks"])
term("whip", "whip", "flex", "car; also cooking drugs, a dance", ["whip", "whips", "whippin", "whipping"], poly=True)
term("gangstawalk", "gangsta walk", "dance", "Memphis dance", phrases=[r"gangsta walk", r"gangster walk"], region="Memphis")
term("ghostride", "ghost ride", "dance", "Bay Area car stunt", ["ghostride", "ghostridin"], phrases=[r"ghost ?rid(?:e|in|ing)"], region="Bay Area")
term("godumb", "go dumb", "party", "go wild (Bay Area)", phrases=[r"go(?:in|ing|ne)? dumb"], region="Bay Area")
term("bounce", "bounce", "party", "New Orleans bounce music; to leave", ["bounce"], poly=True, region="New Orleans")
term("screwed", "screwed and chopped", "party", "slowed DJ Screw style", phrases=[r"screwed (?:and|n|&) chopped", r"screwed up"], region="Houston")
